✨ Attempting to apply the following manifest:

apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  backoffLimit: 0
  template:
    spec:
      volumes:
      - name: data-input
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
      containers:
      - name: init
        image: google/cloud-sdk:275.0.0-alpine
        command: ["sh", "-c", "gsutil -m rsync -dr gs://glow-sportradar/ /data/input"]
        volumeMounts:
        - mountPath: /data/input
          name: data-input
        imagePullPolicy: IfNotPresent
      restartPolicy: Never

